import type { Metadata } from "next";
import { UserProvider } from "@auth0/nextjs-auth0/client";
// import {}
import "./globals.css";
import Footer from "@/components/Footer/Footer";
import NavBar from "@/components/NavBar/NavBar";

//Contexto
import { CartProvider } from "@/context/CartContext";
import { AuthProvider } from "@/context/Authcontext";
import { BrowserRouter } from 'react-router-dom';

export const metadata: Metadata = {
  title: "Cybergames",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-backgroundLayout">
        <UserProvider>
          <AuthProvider>
            <CartProvider>
              {/* <BrowserRouter> */}
              <NavBar />
              {children}
              <Footer />
              {/* </BrowserRouter> */}
            </CartProvider>
          </AuthProvider>
        </UserProvider>
      </body>
    </html>
  );
}
