import type { Metadata } from "next";
import { UserProvider } from '@auth0/nextjs-auth0/client'
import "./globals.css";
import Footer from "@/components/Footer/Footer";
import NavBar from "@/components/NavBar/NavBar";

//Contexto
import { CartProvider } from "@/context/CartContext";
import { AuthProvider } from "@/context/Authcontext";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-backgroundLayout">
      <AuthProvider>
      <UserProvider>
        <CartProvider>
          <NavBar/>
          {children}
          <Footer/>
        </CartProvider>
        </UserProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
